language: node_js

addons:
    code_climate:
      repo_token: "cc45b18522d5252d3c37ffc55a81756a70f7d0a2cc530049dda8172c0eb09952"

node_js:
  - node

before_install:
  - cd server && cd v2

install:
  - npm ci

script:
  - npm test

services:
  - postgresql
before_script:
  - npm install codeclimate-test-reporter istanbul -g
  - psql -c "CREATE DATABASE way_farer_test;" -U dev
  - psql -c "CREATE USER dev WITH PASSWORD 'Runfree8418_!*'';" -U dev

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run coverage
